org: davidcher
service: price-compare-client

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: prod
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:GetObject"
        - "s3:PutBucketPolicy"
        - "cloudformation:DescribeStacks"
      Resource: "*"


plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: ${cf:price-compare-tracker-resources-prod.ReactClientAppBucketName}
      localDir: build
      deleteRemoved: true 

resources:
  Resources:
    ReactAppCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: ${cf:price-compare-tracker-resources-prod.ReactClientAppBucketDomainName}
              Id: ReactAppOrigin
              S3OriginConfig: {}
          Enabled: true
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: ReactAppOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
            CachedMethods:
              - GET
              - HEAD
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
          ViewerCertificate:
            CloudFrontDefaultCertificate: true

  Outputs:
    AppURL:
      Value: !Join
        - ""
        - - "https://"
          - !Select [2, !Split ['/', !GetAtt ReactAppCloudFrontDistribution.DomainName]]
      Description: "CloudFront URL of the React app"