org: davidcher
service: prices-track

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:REGION}
  stage: ${opt:stage, 'dev'}
  versionFunctions: false
  memorySize: 2048
  environment:
      STAGE: ${opt:STAGE, 'dev'}
      REGION: ${env:REGION}
      BRIGHT_DATA_SERVICE_ENABLED_LIST: ${env:BRIGHT_DATA_SERVICE_ENABLED_LIST}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
        - lambda:InvokeFunction
        - secretsmanager:GetSecretValue
        - dynamodb:PutItem
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
        - s3:ListBucket
        - states:StartExecution
        - states:DescribeExecution
        - states:StopExecution
        - states:ListExecutions
        - states:DescribeStateMachine
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-step-functions
  - serverless-dotenv-plugin

custom:
  PRICE_TRACK_ITEMS_TABLE_NAME: ${env:PRICE_TRACK_ITEMS_TABLE_NAME}-${self:provider.stage}
  S3_RAW_HTML_RESULT_BUCKET_NAME: ${env:S3_RAW_HTML_RESULT_BUCKET_NAME}-${self:provider.stage}
  S3_EXTRACTED_DATA_BUCKET_NAME: ${env:S3_EXTRACTED_DATA_BUCKET_NAME}-${self:provider.stage}
  PRICE_TRACK_SCHEDULED_ITEMS_TABLE_NAME: ${env:PRICE_TRACK_SCHEDULED_ITEMS_TABLE_NAME}-${self:provider.stage}
  PRICE_TRACK_RESULTS_TABLE_NAME: ${env:PRICE_TRACK_RESULTS_TABLE_NAME}-${self:provider.stage}
  PRICE_TRACK_MACHINE_ARN: ${env:PRICE_TRACK_MACHINE_ARN}
  secrets:
    brightdataProxyUri: sls-fourth/brightdata/proxy/uri
  serverless-offline:
    httpPort: 5005
    lambdaPort: 5018
  build:
    esbuild:
      bundle: true
      minify: true
      sourcemap: true
      target: node18
      platform: node
      concurrency: 10
      exclude: ['node_modules']


layers:
  chromium:
    path: ../layers/chromium
    name: chromium-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs18.x
    description: Chromium layer for Puppeteer
    package:
      include:
        - nodejs/**

  uuidLib:
    path: ../layers/uuid
    name: uuid-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs18.x
    description: Layer with uuid package
    package:
      include:
        - nodejs/**

  cheerio:
    path: ../layers/cheerio
    name: cheerio-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs18.x
    description: Cheerio layer for HTML parsing
    package:
      include:
        - nodejs/**

  awsDataTransfer:
    path: ../layers/aws-sdk/data-transfer
    name: aws-data-transfer-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs18.x
    description: ApiGateWay & SQS layer
    package:
      include:
        - nodejs/**

  awsStorage:
    path: ../layers/aws-sdk/storage
    name: aws-storage-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs18.x
    description: S3 and DynamoDB layer
    package:
      include:
        - nodejs/**

  awsStepFunction:
    path: ../layers/aws-sdk/step-function
    name: aws-step-function-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs18.x
    description: Step Functions layer
    package:
      include:
        - nodejs/**


functions:
  add-price-track-item:
    handler: functions/add-price-track/handler.addPriceTrackItem
    timeout: 29
    layers:
      - { Ref: UuidLibLambdaLayer }
      - { Ref: AwsDataTransferLambdaLayer }
      - { Ref: AwsStorageLambdaLayer }
    environment:
      PRICE_TRACK_SCHEDULED_ITEMS_TABLE_NAME: ${self:custom.PRICE_TRACK_SCHEDULED_ITEMS_TABLE_NAME}
    events:
      - http:
          path: /price-track/add-price-track-item
          method: post
          cors: true

  getScrapeList:
    handler: price-track-machine/handlers/get-scrape-list/handler.getScrapeList
    timeout: 60
    layers:
      - { Ref: AwsStorageLambdaLayer }
      - { Ref: AwsStepFunctionLambdaLayer }
    environment:
      STAGE: ${self:provider.stage}
      REGION: ${self:provider.region}
      PRICE_TRACK_MACHINE_ARN: ${self:custom.PRICE_TRACK_MACHINE_ARN}
      PRICE_TRACK_SCHEDULED_ITEMS_TABLE_NAME: ${self:custom.PRICE_TRACK_SCHEDULED_ITEMS_TABLE_NAME}
      schedule: 
        rate:
          - cron(0 8 * * ? *)
      enabled: false

  scrapeSite:
    handler: price-track-machine/handlers/scrape-site/handler.scrapeSite
    timeout: 300
    layers:
      - { Ref: UuidLibLambdaLayer }
      - { Ref: ChromiumLambdaLayer }
    environment:
      STAGE: ${self:provider.stage}
      REGION: ${self:provider.region}
      BRIGHT_DATA_SERVICE_ENABLED_LIST: ${env:BRIGHT_DATA_SERVICE_ENABLED_LIST}
      S3_RAW_HTML_RESULT_BUCKET_NAME: ${self:custom.S3_RAW_HTML_RESULT_BUCKET_NAME}

  extractData:
    handler: price-track-machine/handlers/extract-data/handler.extractData
    timeout: 30
    layers:
      - { Ref: CheerioLambdaLayer }
      - { Ref: AwsStorageLambdaLayer }
    environment:
      STAGE: ${self:provider.stage}
      REGION: ${self:provider.region}
      S3_RAW_HTML_RESULT_BUCKET_NAME: ${self:custom.S3_RAW_HTML_RESULT_BUCKET_NAME}

  updatePriceTrackHistoryData:
    handler: price-track-machine/handlers/update-price-track/handler.updateHistoryData
    timeout: 30
    layers:
      - { Ref: AwsStorageLambdaLayer }
      - { Ref: UuidLibLambdaLayer }
    environment:
      STAGE: ${self:provider.stage}
      REGION: ${self:provider.region}
      PRICE_TRACK_RESULTS_TABLE_NAME: ${self:custom.PRICE_TRACK_RESULTS_TABLE_NAME}

stepFunctions:
  validate: true
  stateMachines:
    priceTrackMachine:
      name: price-track-machine-${self:provider.stage}
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - Fn::GetAtt: [ PriceTrackLogGroup, Arn ]
      definition:
        Comment: "Scrape price tracking pipeline state machine"
        StartAt: ScrapeSite
        States:
          ScrapeSite:
            Type: Task
            Resource:
              Fn::GetAtt: [ ScrapeSiteLambdaFunction, Arn ]
            ResultPath: "$.stepScrapeSiteResult"
            TimeoutSeconds: 300
            Next: ExtractData

          ExtractData:
            Type: Task
            Resource:
              Fn::GetAtt: [ ExtractDataLambdaFunction, Arn ]
            InputPath: "$.stepScrapeSiteResult"
            Parameters:
              "scrapeInfo.$": "$.scrapeInfo"
              "bucketKey.$": "$.bucketKey"
              "startScrapeDt.$": "$.startScrapeDt"
              "endScrapeDt.$": "$.endScrapeDt"
            ResultPath: "$.stepExtractDataResult"
            Next: SavePriceTrackData

          SavePriceTrackData:
            Type: Task
            Resource:
              Fn::GetAtt: [ UpdatePriceTrackHistoryDataLambdaFunction, Arn ]
            InputPath: "$.stepExtractDataResult"
            Parameters:
              "scrapeInfo.$": "$.scrapeInfo"
              "startScrapeDt.$": "$.startScrapeDt"
              "endScrapeDt.$": "$.endScrapeDt"
              "priceTrackData.$": "$.priceTrackData"
            ResultPath: "$.stepSavePriceTrackData"
            End: true


package:
  individually: true

resources:
  Resources:
    PriceTrackLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/prices-track-machine-${sls:stage}
        RetentionInDays: 14