org: davidcher
service: web-scraper

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  timeout: 60
  stage: ${opt:stage, 'dev'}
  region: ${env:REGION}
  versionFunctions: false
  environment:
    STAGE: ${opt:STAGE, 'dev'}
    REGION: ${env:REGION}
    BRIGHT_DATA_SERVICE_ENABLED_LIST: ${env:BRIGHT_DATA_SERVICE_ENABLED_LIST}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
        - lambda:InvokeFunction
        - secretsmanager:GetSecretValue
        - dynamodb:PutItem
        - sqs:SendMessage
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - s3:GetObject
        - s3:PutObject
        - s3:DeleteObject
        - s3:ListBucket
      Resource: "*"
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-websockets-plugin

custom:
  WS_CONNECTIONS_TABLE_NAME: ${env:WS_CONNECTIONS_TABLE_NAME}-${self:provider.stage}
  RESULT_DB_TABLE_NAME: ${env:RESULT_DB_TABLE_NAME}-${self:provider.stage}
  SQS_SCRAPE_REQUEST: ${env:SQS_SCRAPE_REQUEST}-${self:provider.stage}
  SQS_HTML_RAW_DATA_RESULT: ${env:SQS_HTML_RAW_DATA_RESULT}-${self:provider.stage}
  SQS_EXTRACTED_DATA: ${env:SQS_EXTRACTED_DATA}-${self:provider.stage}
  S3_RAW_HTML_RESULT_BUCKET_NAME: ${env:S3_RAW_HTML_RESULT_BUCKET_NAME}-${self:provider.stage}
  S3_EXTRACTED_DATA_BUCKET_NAME: ${env:S3_EXTRACTED_DATA_BUCKET_NAME}-${self:provider.stage}
  SQS_SCRAPE_DLQ: ${env:SQS_SCRAPE_DLQ}-${self:provider.stage}
  secrets:
    brightdataProxyUri: sls-fourth/brightdata/proxy/uri
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node18
    packager: npm
    platform: node
    concurrency: 10
    tsconfig: './tsconfig.base.json'
    excludeDevDependencies: true
    external:
      - shared/SQSService.ts
    resolveExtensions:
      - .js
      - .ts
  serverless-offline:
    httpPort: 5002


resources:
  Resources:
    ScrapeRequestQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.SQS_SCRAPE_REQUEST}
        VisibilityTimeout: 70
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [DLQ, Arn]
          maxReceiveCount: 1
    ScrapeHtmlRawDataQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.SQS_HTML_RAW_DATA_RESULT}
        VisibilityTimeout: 70
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [DLQ, Arn]
          maxReceiveCount: 1
    ScrapeExtractedResultsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.SQS_EXTRACTED_DATA}
        VisibilityTimeout: 70
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt: [DLQ, Arn]
          maxReceiveCount: 1
    DLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.SQS_SCRAPE_DLQ}

    ScrapedHtmlBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.S3_RAW_HTML_RESULT_BUCKET_NAME}
    ExtractedDataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.S3_EXTRACTED_DATA_BUCKET_NAME}

    WsScrapeStatusConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.WS_CONNECTIONS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    UserScrapesResultsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user-scrape-results-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: scrapeId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
          - AttributeName: scrapeRequestId
            AttributeType: S
        KeySchema:
          - AttributeName: scrapeId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: user-id-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: scrape-request-id-index
            KeySchema:
              - AttributeName: scrapeRequestId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST

layers:
  chromium:
    path: ../layers/chromium
    name: chromium-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs18.x
    description: Chromium layer for Puppeteer
    package:
      include:
        - nodejs/**

  uuidLib:
    path: ../layers/uuid
    name: uuid-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs18.x
    description: Layer with uuid package
    package:
      include:
        - nodejs/**

  awsStorage:
    path: ../layers/aws-sdk/storage
    name: aws-storage-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs18.x
    description: S3 and DynamoDB layer
    package:
      include:
        - nodejs/**

  awsDataTransfer:
    path: ../layers/aws-sdk/data-transfer
    name: aws-data-transfer-layer-${sls:stage}
    compatibleRuntimes:
      - nodejs18.x
    description: ApiGateWay & SQS layer
    package:
      include:
        - nodejs/**

functions:
  acceptRequest:
    handler: functions/formScrape/handler.formScrapeRequest
    package:
      individually: true
      include:
        - functions/formScrape/**
        - commons/**
    timeout: 29
    environment:
      STAGE: ${self:provider.stage}
      REGION: ${self:provider.region}
      AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
      SQS_SCRAPE_REQUEST: ${self:custom.SQS_SCRAPE_REQUEST}
    layers:
    - { Ref: UuidLibLambdaLayer }
    - { Ref: AwsDataTransferLambdaLayer }
    events:
      - http:
          path: /scrape-service/scrape
          method: post
          cors: true
          # request:
          #   schemas:
          #     application/json: ${file(./models/scrape-request-schema.json)}

  scraper:
    handler: functions/puppeteer/handler.handleSqsMessage
    package:
      individually: true
      include:
        - functions/puppeteer/**
        - commons/**
    environment:
      S3_RAW_HTML_RESULT_BUCKET_NAME: ${self:custom.S3_RAW_HTML_RESULT_BUCKET_NAME}
      CHROMIUM_PATH: "/tmp/chromium"
      STAGE: ${self:provider.stage}
      AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
      REGION: ${self:provider.region}
      SQS_SCRAPE_REQUEST: ${self:custom.SQS_SCRAPE_REQUEST}
      SQS_HTML_RAW_DATA_RESULT: ${self:custom.SQS_HTML_RAW_DATA_RESULT}
      RESULT_DB_TABLE_NAME: ${self.custom.RESULT_DB_TABLE_NAME}
      BRIGHT_DATA_SERVICE_ENABLED_LIST: ${self:provider.environment.BRIGHT_DATA_SERVICE_ENABLED_LIST}
      SECRET_MANAGER_ADDRESS: ${env:SECRET_MANAGER_ADDRESS}
      SECRET_MANAGER_KEY: ${env:SECRET_MANAGER_KEY}
    layers:
      - { Ref: UuidLibLambdaLayer }
      - { Ref: AwsDataTransferLambdaLayer }
      - { Ref: AwsStorageLambdaLayer }
      - { Ref: ChromiumLambdaLayer }
    timeout: 300
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ScrapeRequestQueue
              - Arn

  extract-data:
    handler: functions/data-extractor/handler.handleSqsMessage
    package:
      individually: true
      include:
        - functions/data-extractor/**
        - commons/**
    environment:
      S3_RAW_HTML_RESULT_BUCKET_NAME: ${self:custom.S3_RAW_HTML_RESULT_BUCKET_NAME}
      STAGE: ${self:provider.stage}
      REGION: ${self:provider.region}
      S3_EXTRACTED_DATA_BUCKET_NAME: ${self:custom.S3_EXTRACTED_DATA_BUCKET_NAME}
      SQS_EXTRACTED_DATA: ${self:custom.SQS_EXTRACTED_DATA}
    layers:
      - { Ref: AwsDataTransferLambdaLayer }
      - { Ref: AwsStorageLambdaLayer }
    timeout: 60
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ScrapeHtmlRawDataQueue
              - Arn

  save-extracted-data:
    handler: functions/save-scrape-result/handler.handleSqsMessage
    package:
      individually: true
      include:
        - functions/save-scrape-result/**
        - commons/**
    layers:
    - { Ref: AwsStorageLambdaLayer }
    environment:
      STAGE: ${self:provider.stage}
      REGION: ${self:provider.region}
      S3_EXTRACTED_DATA_BUCKET_NAME: ${self:custom.S3_EXTRACTED_DATA_BUCKET_NAME}
      RESULT_DB_TABLE_NAME: ${self:custom.RESULT_DB_TABLE_NAME}
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ScrapeExtractedResultsQueue
              - Arn

package:
  individually: true
  exclude:
    - scripts/**
    - mock-data/**
  patterns:
    - '!**/*.test.js'
    - '!**/*.spec.js'
    - '!**/__tests__/**'
    - '!**/docs/**'
    - '!**/README.md'
    - '!**/.env'