org: davidcher

service: sls-prices-track-machine

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  memorySize: 2048
  environment:
    IS_LOCAL: ${env:IS_LOCAL, 'false'}
    S3_BUCKET_NAME: ${env:BUCKET_NAME}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - states:StartExecution
        - lambda:InvokeFunction
        - s3:*
        - logs:*
        - dynamodb:*
      Resource: "*"

plugins:
  - serverless-offline
  - serverless-step-functions
  - serverless-step-functions-offline
  - serverless-dotenv-plugin

custom:
  includeDependencies:
    forceInclude:
      - kind-of
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    packager: npm
    exclude: [ 'aws-sdk' ]
    separateBuilds: true
    platform: node
    concurrency: 10
    tsconfig: './tsconfig.base.json'
    include:
      - handlers/extract-data/**
      - handlers/get-scrape-list/**
      - handlers/scrape-site/**
      - handlers/update-price-track/**
  stepFunctionsOffline:
    stateMachines:
      scrapePriceTrackMachine: scrapePriceTrackMachine
    port: 4010
    GetScrapeList: getScrapeList
    ScrapeSite: scrapeSite
    ExtractData: extractData
    SavePriceTrackData: updateHistoryData

functions:
  getScrapeList:
    handler: handlers/get-scrape-list/getScrapeList.handler
    timeout: 30
#    events:
#      - http:
#          path: start-workflow
#          method: post
#          cors: true

  scrapeSite:
    handler: handlers/scrape-site/scrapeSite.handler
    timeout: 30
    package:
      include:
        - handlers/scrape-site/node_modules/**
        - handlers/scrape-site/**

  extractData:
    handler: handlers/extract-data/scrapeFromData.handler
    timeout: 30

  updateHistoryData:
    handler: handlers/update-price-track/updateHistoryData.handler
    timeout: 30

stepFunctions:
  validate: true
  stateMachines:
    scrapePriceTrackMachine:
      name: priceTrackRecord
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - Fn::GetAtt: [ SLSLogGroup, Arn ]
      definition:
        Comment: "Scrape price tracking pipeline state machine"
        StartAt: GetScrapeList
        States:
          GetScrapeList:
            Type: Task
            Resource:
              Fn::GetAtt: [ GetScrapeListLambdaFunction, Arn ]
            ResultPath: "$.stepGetScrapeListResult"
            Next: iterateScrapeList

          iterateScrapeList:
            Type: Map
            ItemsPath: "$.stepGetScrapeListResult.scrapeList"
            Parameters:
              "scrapeInfo.$": "$$.Map.Item.Value"
              "userId.$": "$.stepGetScrapeListResult.userId"
            MaxConcurrency: 5
            Iterator:
              StartAt: ScrapeSite
              States:

                ScrapeSite:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [ ScrapeSiteLambdaFunction, Arn ]
                  Parameters:
                    "scrapeInfo.$": "$.scrapeInfo"
                    "userId.$": "$.userId"
                  ResultPath: "$.stepScrapeSiteResult"
                  TimeoutSeconds: 30
                  Next: ExtractData

                ExtractData:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [ ExtractDataLambdaFunction, Arn ]
                  InputPath: "$.stepScrapeSiteResult"
                  ResultPath: "$.stepExtractDataResult"
                  Next: SavePriceTrackData

                SavePriceTrackData:
                  Type: Task
                  Resource:
                    Fn::GetAtt: [ UpdateHistoryDataLambdaFunction, Arn ]
                  InputPath: "$.stepExtractDataResult"
                  ResultPath: "$.stepSavePriceTrackData"
                  End: true
            End: true

package:
  individually: true

resources:
  Resources:
    ScrapedHtmlBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}
    SLSLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: /aws/lambda/sls-prices-track-machine
        RetentionInDays: 14